### PR TITLE
fix(cluster): periodically sync against known members

### LINKED ISSUE #16: Events not always gossipped to all nodes
With a gossip fan out smaller than the cluster size, it's possible that some gossip updates are not propagated to the whole cluster if nodes keep picking the same nodes over and over.

During our test we get the following gossip pattern:

`zeebe-0`:
```
13:00:29.630 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}}
13:00:29.634 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=1, address=zeebe-1.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":1,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-1.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":true,"2":true,"5":false,"6":false,"7":true}}}}
```

`zeebe-1`:
```
13:00:29.751 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 1 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=2, address=zeebe-2.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":2,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-2.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"2":false,"3":true,"6":true,"7":false,"8":false}}}}
13:00:29.751 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 1 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}}
```

`zeebe-2`:
```
13:00:29.924 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 2 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}}
13:00:29.927 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 2 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=1, address=zeebe-1.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":1,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-1.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":true,"2":true,"5":false,"6":false,"7":true}}}}
```

`zeebe-3`:
```
```

`zeebe-4`:
```
13:00:29.820 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 4 - Gossipping updates [Member{id=0, address=zeebe-0.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":0,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-0.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"4":true,"5":true,"6":false}}}, version=3.2.0-alpha1, timestamp=1561033847627, state=ALIVE, incarnationNumber=1561033847630}] to Member{id=0, address=zeebe-0.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":0,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-0.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"4":true,"5":true,"6":false}}}}
13:00:33.820 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 4 - Gossipping updates [Member{id=2, address=zeebe-2.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":2,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-2.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"2":false,"3":true,"6":true,"7":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846670, state=ALIVE, incarnationNumber=1561033846672}] to Member{id=2, address=zeebe-2.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":2,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-2.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"2":false,"3":true,"6":true,"7":false,"8":false}}}}
13:00:33.822 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 4 - Gossipping updates [Member{id=2, address=zeebe-2.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":2,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-2.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"2":false,"3":true,"6":true,"7":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846670, state=ALIVE, incarnationNumber=1561033846672}] to Member{id=0, address=zeebe-0.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":0,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-0.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"4":true,"5":true,"6":false}}}}
13:00:34.820 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 4 - Gossipping updates [Member{id=1, address=zeebe-1.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":1,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-1.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":true,"2":true,"5":false,"6":false,"7":true}}}, version=3.2.0-alpha1, timestamp=1561033846747, state=ALIVE, incarnationNumber=1561033846750}] to Member{id=0, address=zeebe-0.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":0,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-0.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"4":true,"5":true,"6":false}}}}
13:00:34.821 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 4 - Gossipping updates [Member{id=1, address=zeebe-1.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":1,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-1.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":true,"2":true,"5":false,"6":false,"7":true}}}, version=3.2.0-alpha1, timestamp=1561033846747, state=ALIVE, incarnationNumber=1561033846750}] to Member{id=1, address=zeebe-1.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":1,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-1.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":true,"2":true,"5":false,"6":false,"7":true}}}}
```

### PR DESCRIPTION
**Pull request by npepinpe**
**Description:**

- periodically syncs against a list of known members

**Related issues:**

closes #16

### CODE REVIEW

**Comment by npepinpe** [comment]
Some notes:

1. Seems like the cluster code isn't according to our format, so there's some noise there :(
1. I'm not happy with the test - first, it doesn't test everything, just the basic functionality, and second, I had to expose a property for testing :( - if you have any ideas I'm all ears

**Comment by npepinpe** [comment]
Thanks for the comments, I updated to a better test that doesn't require us to expose anything.

General idea is:

1. Start a cluster of 3 nodes
1. Disconnect node 3 from the others
1. Update node1 with a new property
1. Wait for it to be completely propagated (e.g. node 2 has received it __and__ attempted to propagate it)
1. Reconnect node 2 and 3 (but not node 1 to avoid it probing node 3 and updating it)

The only way for node 3 to receive node 1's new property would then be for it to sync with node 2.

NOTE: I'm not very happy about using `Thread.sleep` :( the alternative was exposing a few more things (namely the messaging topics and the serializer) in order to listen on the unicast service for the sync requests, but that also comes with its downsides =/

**Review by saig0 — APPROVED** [review]
:+1: I like it

**Comment by npepinpe** [comment]
Thanks :tada:

**Pull request merged**
