### PR TITLE
test(raft): add test to verify heartbeats

### PR DESCRIPTION
**Pull request by ChrisKujawa**
Just wanted to have an test such that we make sure that the heartbeats are always sent.
Not 100% sure if it makes sense to write this based on the metrics. What do you think?

closes #https://github.com/zeebe-io/atomix/issues/40

### CODE REVIEW

**Comment by ChrisKujawa** [comment]
**Copied:**
_npepinpe commented 1 hour ago_

Hm, wouldn't failure detection essentially test this? If we had a way to cause the heart beat to not be sent without actually shutting down the node, then we could test this more explicitly maybe?

**Comment by ChrisKujawa** [comment]
> Hm, wouldn't failure detection essentially test this?

Currently we don't test that leader change doesn't happen after higher load.

> If we had a way to cause the heart beat to not be sent without actually shutting down the node, then we could test this more explicitly maybe?

Not sure If I get this. Actually I don't want code in productive code only for test purposes.

We can also close this was just an idea :)

**Comment by npepinpe** [comment]
I agree, I'd rather avoid writing code only for tests; I was wondering if we already have a way to do this. The feature is failure detection, so I feel like that's what we should be testing, i.e. no heartbeats mean leader is detected as failed. If it's too complicated to write a test for this then this PR is definitely an improvement on the current state

**Review by npepinpe — APPROVED** [review]
In the `RaftTest`, don't we use a test protocol? Could we sever the heartbeat? That would make it fail, and we should then detect failover, right? Though that's also not a great test since it relies on timing...

Maybe metrics is the best we can do for now.

**Pull request merged**
