### PR TITLE
chore(raft): handle additional failures on install RPC

### LINKED ISSUE #196: Abort pending snapshot on snapshot install failures
**Expected behavior**

If there is an expected error during the snapshot install RPC, we should handle it properly by logging it and aborting the current replication. By expected errors we refer to exceptional cases (e.g. I/O errors), not business logic error (e.g. wrong term).

1. Failure to write the snapshot chunk
1. Failure to commit the pending snapshot
1. Failure to abort the pending snapshot

**Actual behavior**

At the moment, if we fail to write the pending snapshot chunk, the follower will fail and report its state as unhealthy, throwing an exception. Failure on commit is currently already handled.

**Steps to reproduce**

Difficult to do with code without exposing everything, but in practice, it can happen that someone else accesses the snapshot chunk (e.g. another thread is removing "orphaned" pending snapshots), as we're trying to write, causing an I/O exception to be thrown.

### PR DESCRIPTION
**Pull request by npepinpe**
**Description**

Adds additional error handling in `PassiveRole#onInstall` to handle when:

1. The request is not the last request (`request.complete() == false`) yet it does not provide a next snapshot chunk (this is based from a leftover comment which suggested this check but had no implemented it for some reason)
1. The chunk fails to be written, at which point we log the error and return an appropriate response

Closes #196

### CODE REVIEW

**Comment by npepinpe** [comment]
I tried writing a test for this, but ended up having to mock too much - any thoughts? I'm not sure how to somehow test that the file cannot be written, as the default Atomix implementation uses temporary files (so hard to predict where they will be written), and even then it's quite difficult to inject failures without mocking the whole thing (which results in an ungodly amount of mocks :disappointed_relieved:).

**Comment by npepinpe** [comment]
Also this is missing handling on abort, I'll add it in a bit.

**Comment by npepinpe** [comment]
Done - all that's missing would be testing, but apart from a heavily mocked test, I'm all out of ideas, and I'm not sure of the value of such a mocked test.

**Review by deepthidevaki — APPROVED** [review]
:+1: Did you run a benchmark with this?

**Comment by npepinpe** [comment]
Not yet - I want to see on the Zeebe side if we need something similar in our own snapshot replication.

**Comment by npepinpe** [comment]
See: https://github.com/zeebe-io/zeebe/pull/4108#issuecomment-602648109

Basically I ran into other known issues, but replication seemed OK - it caught one failure (failed to write pending snapshot chunk) and handled it properly, but I didn't get to see the others.

**Pull request merged**
