### PR TITLE
First step in clean up atomix repo

### PR DESCRIPTION
**Pull request by ChrisKujawa**
I did the first step in clean up a bit the atomix repo and removed everything which we don't need or use.

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by npepinpe** [comment]
There's some `NoSuchMethodError` in one of the builds, not sure if related to the PR?

**Comment by ChrisKujawa** [comment]
Yes i have to clean up a bit more😅😀

**Comment by ChrisKujawa** [comment]
Hey @npepinpe I updated the PR and removed the primitives as well.

**Comment by npepinpe** [comment]
I thought I'd approved it, but I guess you were waiting for a second approval :sweat_smile: 

Sorry about that!

**Review by npepinpe — APPROVED** [review]

**Comment by ChrisKujawa** [comment]
Ok. I gave it another try. I removed all primitives from the core module. 

I decided to keep the primitive module, since it is now only and completely used by the raft module. I tried to delete it, but I found out that actually everything is used in the Raft impl. It seem to be really hard coupled and it is almost impossible to remove it completely without rewriting everything. I think both modules could be merged or we decided to rewrite the complete raft :sweat_smile: But this could be postpone I think.

Still I was able to delete -90k lines. :man_shrugging: :smile:

**Comment by npepinpe** [comment]
What is the dependency on the Raft side to the primitives? If it's mostly in the unused stuff from the Zeebe side (e.g. RaftServiceManager and the services, system partition stuff, partition service, etc.), then we know how to remove it, so we can merge as long as we commit to doing the other steps to remove it: drop system partition, rewrite partitioning service, drop old Atomix implementations of SnapshotStore and RaftServiceManager, etc.

**Comment by ChrisKujawa** [comment]
> What is the dependency on the Raft side to the primitives? If it's mostly in the unused stuff from the Zeebe side (e.g. RaftServiceManager and the services, system partition stuff, partition service, etc.), then we know how to remove it, so we can merge as long as we commit to doing the other steps to remove it: drop system partition, rewrite partitioning service, drop old Atomix implementations of SnapshotStore and RaftServiceManager, etc.

Actually yes but I can't do it in this repo I think, becuase without the RaftServiceManager impl this complete system doesnt make sense ^^. I tried to remove the RaftServiceManager but there also lots of Service and Session classes which used there, like in LeaderRole or other Raft related classes. It is totally messed up. I had the feeling to be safer for now I will keep it and then we can try it later again.

**Pull request merged**
