### PR TITLE
Fix duplicated retries

### LINKED ISSUE #22: High latency and resource consumption due to retry requests
Please see original issues for more information https://github.com/zeebe-io/zeebe/issues/2778

**Expected behavior**

On high load no weird latency pattern.

**Actual behavior**

We saw in our APP latency pattern like this and the root cause seems to be atomix.

```
$ ghz -insecure --proto ./gateway-protocol/src/main/proto/gateway.proto --call gateway_protocol.Gateway.CreateWorkflowInstance -d '{"workflowKey": 2251799813685249}' -n 2000 localhost:26500

Summary:
  Count:        2000
  Total:        73683.84 ms
  Slowest:      5075.27 ms
  Fastest:      25.08 ms
  Average:      1742.50 ms
  Requests/sec: 27.14

Response time histogram:
  25.077 [1]    |
  530.096 [1339]|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  1035.115 [0]  |
  1540.135 [0]  |
  2045.154 [0]  |
  2550.173 [0]  |
  3055.192 [0]  |
  3560.211 [0]  |
  4065.230 [0]  |
  4570.249 [0]  |
  5075.268 [660]|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎

Latency distribution:
  10% in 60.69 ms
  25% in 116.77 ms
  50% in 157.56 ms
  75% in 5019.84 ms
  90% in 5039.01 ms
  95% in 5048.32 ms
  99% in 5061.54 ms
Status code distribution:
  [OK]  2000 responses
```

We wrote an test example and this seem to block often (kind of deadlock) and mostly end in out of memory.

**Minimal yet complete reproducer code (or URL to code)**

```java
package io.atomix.protocols.raft.test;

import io.atomix.cluster.MemberId;
import io.atomix.cluster.Node;
import io.atomix.cluster.discovery.BootstrapDiscoveryProvider;
import io.atomix.core.Atomix;
import io.atomix.core.list.AsyncDistributedList;
import io.atomix.protocols.raft.partition.RaftPartitionGroup;
import io.atomix.storage.StorageLevel;

import java.io.File;
import java.time.Duration;
import java.time.Instant;
import java.util.Arrays;
import java.util.concurrent.CountDownLatch;

public class LatencyTest {
  public static void main(String[] args) throws InterruptedException {
    new LatencyTest().run();
  }

  private final MemberId member = MemberId.anonymous();
  public void run() throws InterruptedException {
    final RaftPartitionGroup system =
        RaftPartitionGroup.builder("system")
            .withMembers(member)
            .withNumPartitions(1)
            .withPartitionSize(1)
            .withDataDirectory(new File(String.format("target/perf-logs/%s/system", member.id())))
            .build();
    final RaftPartitionGroup data =
        RaftPartitionGroup.builder("data")
            .withMembers(member)
            .withNumPartitions(1)
            .withPartitionSize(1)
            .withStorageLevel(StorageLevel.DISK)
            .withFlushOnCommit(false)
            .withDataDirectory(new File(String.format("target/perf-logs/%s/data", member.id())))
            .build();

    final Atomix atomix =
        Atomix.builder()
            .withMemberId(member)
            .withShutdownHookEnabled()
            .withMembershipProvider(
                BootstrapDiscoveryProvider.builder()
                    .withNodes(Node.builder().withId(member.id()).build())
                    .build())
            .withManagementGroup(system)
            .withPartitionGroups(data)
            .build();

    atomix.start().join();

    final AsyncDistributedList<Integer> list = atomix.<Integer>getList("list").async();

    // warmup
    System.out.println("Warming up");
    final int warmUpCount = 1000;
    final CountDownLatch warmUpLatch = new CountDownLatch(warmUpCount);
    for (int i = 0; i < warmUpCount; i++) {
      list.add(1).thenRun(warmUpLatch::countDown);
    }
    warmUpLatch.await();
    list.clear().join();
    System.out.println("Finished warming up");

    final int workCount = 15_000;
    final long[] latencies = new long[workCount];
    final CountDownLatch latch = new CountDownLatch(workCount);
    for (int i = 0; i < workCount; i++) {
      final Instant now = Instant.now();
      final int index = i;
      list.add(i, i)
          .whenComplete(
              (nothing, error) -> {
                final Duration between = Duration.between(now, Instant.now());
                latencies[index] = between.toMillis();
//                if (between.compareTo(Duration.ofSeconds(5)) >= 0) {
//                  System.out.println("one request has latency at least greater than one second " + between.toString());
//                }
                if (index % 100 == 0) {
                  System.out.println("Counted down " + index);
                }
                latch.countDown();
              });
    }

    latch.await();

    final int[] buckets = new int[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    for (int i = 0; i < workCount; i++) {
      if (latencies[i] < 10_000) {
        buckets[(int)Math.floorDiv(latencies[i], 1000)]++;
      } else {
        buckets[9]++;
      }
    }

    System.out.println("Finished, latencies grouped in order: " + Arrays.toString(buckets));
  }
}
```

**Environment**

 - Atomix: 3.1.5 [e.g. 3.0.0]
 - OS: Linux zell-arch 5.1.16-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 3 20:23:07 UTC 2019 x86_64 GNU/Linux
 [e.g. `uname -a`]
 - JVM 8 [e.g. `java -version`]

### PR DESCRIPTION
**Pull request by ChrisKujawa**
* fixes the duplicated retries
 * removes unnecessary collecting of pending commands

closes #22

### CODE REVIEW

**Comment by npepinpe** [comment]
I updated the test; I noticed that before it was sometimes passing even without the fix, since it relied on scheduling and we only waited until x amounts of futures were there. This is what I came up to make it reliable, but it feels...over-complicated? I'd appreciate if you have any ideas to make it simpler. 

I'm assigning @menski as well so @Zelldon you don't have to work more to review my changes

**Comment by ChrisKujawa** [comment]
Hey @npepinpe thanks for fixing the test, but yes it feels a way to complicated.

I could just update the test with a few different lines if you like, this would make the test also reliable. 
The key points are using verify and the property that the thread pool context will execute tasks in order.
```java
  @Test
  public void testReSubmitCommand() throws Throwable {
    // given
    // setup  thread context
    final Logger log = LoggerFactory.getLogger(getClass());
    final int threadPoolSize = Math.max(Math.min(Runtime.getRuntime().availableProcessors() * 2, 16), 4);
    final ThreadContext context = spy(new BlockingAwareThreadPoolContextFactory(
        "raft-partition-group-data-%d", threadPoolSize, log).createContext());

    // collecting request futures
    final List<CompletableFuture<CommandResponse>> futures = new CopyOnWriteArrayList<>();
    final List<Long> sequences = new CopyOnWriteArrayList<>();
    final RaftSessionConnection connection = mock(RaftSessionConnection.class);
    when(connection.command(any(CommandRequest.class)))
        .thenAnswer(invocationOnMock -> {
          final CommandRequest commandRequest = (CommandRequest) invocationOnMock.getArguments()[0];
          sequences.add(commandRequest.sequenceNumber());
          final CompletableFuture<CommandResponse> future = new CompletableFuture<>();
          futures.add(future);
          return future;
        });

    // raft session invoker
    final RaftSessionState state = new RaftSessionState("test", SessionId.from(1), UUID.randomUUID().toString(), TestPrimitiveType.instance(), 1000);
    final RaftSessionManager manager = mock(RaftSessionManager.class);
    final RaftSessionInvoker submitter =
        new RaftSessionInvoker(connection,
            mock(RaftSessionConnection.class),
            state,
            new RaftSessionSequencer(state),
            manager,
            context);


    // send five commands
    submitter.invoke(operation(COMMAND, HeapBytes.EMPTY));
    submitter.invoke(operation(COMMAND, HeapBytes.EMPTY));
    submitter.invoke(operation(COMMAND, HeapBytes.EMPTY));
    submitter.invoke(operation(COMMAND, HeapBytes.EMPTY));
    final CompletableFuture<byte[]> lastFuture = submitter.invoke(operation(COMMAND, HeapBytes.EMPTY));

    verify(connection, timeout(2000).times(5)).command(any());

    // when we missed second command
    futures.get(0).complete(CommandResponse.builder()
        .withStatus(RaftResponse.Status.OK)
        .withIndex(10)
        .withResult("Hello world!".getBytes())
        .build());
    final ArrayList<CompletableFuture<CommandResponse>> copiedFutures = new ArrayList<>(futures.subList(1, futures.size()));
    futures.clear();
    sequences.clear();
    copiedFutures.forEach(f ->
      f.complete(CommandResponse.builder()
          .withStatus(RaftResponse.Status.ERROR)
          .withError(RaftError.Type.COMMAND_FAILURE)
          .withLastSequence(1)
          .build()));

    // then session invoker should resubmit 4 commands
    verify(connection, timeout(2000).times(9)).command(any());
    final CountDownLatch latch = new CountDownLatch(1);
    // context thread pool ensures execution of task in order
    context.execute(latch::countDown);
    latch.await();

    assertEquals(4, futures.size());
    assertArrayEquals(new Long[]{2L, 3L, 4L, 5L}, sequences.toArray(new Long[0]));

    futures.forEach(f -> f.complete(CommandResponse.builder()
            .withStatus(RaftResponse.Status.OK)
            .withIndex(10)
            .withResult("Hello world!".getBytes())
            .build()));

    assertArrayEquals(lastFuture.get(), "Hello world!".getBytes());
    assertEquals(5, state.getCommandRequest());
    assertEquals(5, state.getCommandResponse());
    assertEquals(10, state.getResponseIndex());
  }
```

**Comment by npepinpe** [comment]
Yes, I was tired and just wanted to wrap it up yesterday night, mocks are much easier to use here, though I guess there's still a tiny chance that the threads are not scheduled and the test pass? Still better than what I came up with haha

I think you could also use a single thread context instead of the blocking one? Or am I missing something?

**Comment by ChrisKujawa** [comment]
> Yes, I was tired and just wanted to wrap it up yesterday night, mocks are much easier to use here, though I guess there's still a tiny chance that the threads are not scheduled and the test pass?

No there a two barriers. First one is verify, which fails without the fix because it is called more than 9 times and then we have the `context.execute`, which enqueues and task. The thread pool executes the tasks in order, which means if the count down latch is done, all other are done as well. Then we check the sequences, which would have more then 4 entries.

I wanted to use the same setting, which we use in the normal setup that is the reason why I used this context/pool.

**Comment by npepinpe** [comment]
My bad, I'm reading this on mobile and the formatting is messed up in my browser, just glanced at it and saw the use of mocks but didn't noticed the count down latch. I'll stop reviewing on mobile :sweat_smile:

**Comment by ChrisKujawa** [comment]
Ok updated the branch - builds are green :v:

**Review by npepinpe — APPROVED** [review]
:tada:

**Comment by npepinpe** [comment]
bors retry

**Pull request merged**
