### PR TITLE
chore(raft): include term in role change listeners

### PR DESCRIPTION
**Pull request by deepthidevaki**
* Add new RaftRoleChangeListener interface which accepts both role and term

Related to https://github.com/zeebe-io/zeebe/issues/3697

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1: 

Did you test that it won't break current implementations?

**Comment by deepthidevaki** [comment]
> Did you test that it won't break current implementations?

It works after updating interface.

**Comment by deepthidevaki** [comment]
@npepinpe I changed the interface. This is better. Otherwise, RoleChangeListener must implement both methods.

**Review by npepinpe — APPROVED** [review]
Nice one :+1:

**Pull request merged**
