### PR TITLE
chore(storage): close readers

### PR DESCRIPTION
**Pull request by ChrisKujawa**
* closes unused readers - reduces footprint when we can't delete segments

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
Just to be sure I'm right, before we weren't closing the current reader when moving on to a new segment, just replacing it? And that caused some resources it allocated to not be closed since it wasn't be `#close()`?

**Comment by ChrisKujawa** [comment]
Correct. Eventually they are closed because the segment is closed since it is deleted but if this is not happening, as in my benchmarks then they live forever.

**Review by npepinpe — APPROVED** [review]
:tada:

**Pull request merged**
