### PR TITLE
notify role change after initial entries are commiited

### PR DESCRIPTION
**Pull request by deepthidevaki**
* Delays the notification of role change to leader after the initial entries are committed. This is required for zeebe as zeebe leader, on start, expects the log that it reads to be up to date. With out this, a zeebe leader may incorrectly reads an older entry as the last one, while there are uncommitted entries following it.

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
Nice thanks 👍🎉

**Comment by jwulf** [comment]
Does this address #3920? 

https://github.com/zeebe-io/zeebe/issues/3920

**Comment by deepthidevaki** [comment]
Yes. We are testing it.

**Pull request merged**
