### PR TITLE
chore(raft): apply flushOnCommit to Journal

### PR DESCRIPTION
**Pull request by npepinpe**

### CODE REVIEW

**Comment by npepinpe** [comment]
It was previously setting `flushOnCommit` on the `RaftLog`, which was then not used; it's also a parameter on the `Journal`, and it seems we just weren't setting it through the normal configuration; this should fix that. I can't speak as to whether or not it will help your [issue](https://github.com/zeebe-io/zeebe/issues/3266), but it might :+1:

**Comment by ChrisKujawa** [comment]
Either the ZeebeTests are flaky or this change breaks it, which I don't expect. I re-triggered it.


```
[ERROR] Failures: 

[ERROR] io.atomix.protocols.raft.zeebe.ZeebeTest.shouldNotifyCommitListeners[single node](io.atomix.protocols.raft.zeebe.ZeebeTest)

[ERROR]   Run 1: ZeebeTest.shouldNotifyCommitListeners:239 expected:<1> but was:<0>

[ERROR]   Run 2: ZeebeTest.shouldNotifyCommitListeners:239 expected:<1> but was:<0>

[ERROR]   Run 3: ZeebeTest.shouldNotifyCommitListeners:239 expected:<1> but was:<0>

[ERROR]   Run 4: ZeebeTest.shouldNotifyCommitListeners:239 expected:<1> but was:<0>

[INFO] 

[ERROR] io.atomix.protocols.raft.zeebe.ZeebeTest.shouldNotifyCommitListeners[three nodes](io.atomix.protocols.raft.zeebe.ZeebeTest)

[ERROR]   Run 1: ZeebeTest.shouldNotifyCommitListeners:239 expected:<3> but was:<2>

[ERROR]   Run 2: ZeebeTest.shouldNotifyCommitListeners:239 expected:<1> but was:<0>

[ERROR]   Run 3: ZeebeTest.shouldNotifyCommitListeners:239 expected:<3> but was:<2>

[ERROR]   Run 4: ZeebeTest.shouldNotifyCommitListeners:239 expected:<1> but was:<0>

[INFO] 
```

**Comment by npepinpe** [comment]
I'll investigate, better not start with flaky tests here as well :see_no_evil:

**Comment by ChrisKujawa** [comment]
Thanks :+1:

**Comment by npepinpe** [comment]
The test is flaky, of course, I can't believe I didn't see it :see_no_evil: I'll post a fix as part of this issue if that's alright

**Comment by ChrisKujawa** [comment]
Nice catch ! It finally flush on commit and the segment creation time goes down. I was always wondering why I saw no segment flash at all :laughing: 

latency

But I think the append latency goes up now, which is probably expected.

**Review by ChrisKujawa — APPROVED** [review]
:+1:

**Pull request merged**
